version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - RCH__WORKER__ENABLE=true
      - RCH__STORAGE__POSTGRES__DB_URL=postgresql://postgres:reacher_password@postgres:5432/reacherdb
      - RCH__WORKER__RABBITMQ__URL=amqp://guest:guest@rabbitmq:5672
      - RCH__WORKER__RABBITMQ__CONCURRENCY=30
      - RCH__THROTTLE__MAX_REQUESTS_PER_MINUTE=60
      - RCH__THROTTLE__MAX_REQUESTS_PER_DAY=10000
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=reacher_password
      - POSTGRES_DB=reacherdb
    volumes:
      - reacher_pg_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - reacher_rmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  reacher_pg_data:
  reacher_rmq_data:
